name: nusopa_mart
description: "Aplikasi Marketplace Nusopa Mart Sederhana"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # LIBRARY UNTUK TAMPILAN MEWAH & LOGISTIK DATA NYATA
  google_fonts: ^6.2.0        # Font modern (Inter / Roboto) agar tidak kaku
  url_launcher: ^6.3.0        # Untuk membuka link cek resi logistik di Google Chrome
  image_picker: ^1.1.2        # Untuk seller mengambil foto resi fisik lewat kamera/galeri
  http: ^1.2.2                # Koneksi data nyata dari Flutter ke Backend API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # PENGATURAN ASET (Pastikan folder ini ada di proyek Anda jika ingin pakai gambar lokal)
  assets:
    - assets/icon/
