name: nusopa_mart
description: "Aplikasi Marketplace Nusopa Mart Sederhana"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # LIBRARY VISUAL MEWAH & LOGISTIK
  google_fonts: ^6.2.0        # Font modern agar tidak kaku
  url_launcher: ^6.3.0        # Untuk membuka link pelacakan di Google Chrome
  image_picker: ^1.1.2        # Untuk seller mengambil foto resi fisik lewat kamera
  intl: ^0.19.0               # <-- DITAMBAHKAN DI SINI (Wajib untuk format Rupiah)

  # INTI FIREBASE UNTUK DATA NYATA (SIAP RILIS INTERNET)
  firebase_core: ^3.1.0       # Diperbarui sedikit ke versi minor stabil
  firebase_auth: ^5.1.0       
  cloud_firestore: ^5.1.0     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Pastikan folder 'assets/icon/' sudah Anda buat di komputer sebelum melakukan pub get
  assets:
    - assets/icon/logo.png
