name: nusopa_mart
description: "Aplikasi Marketplace Nusopa Mart Sederhana"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # LIBRARY VISUAL MEWAH & LOGISTIK
  google_fonts: ^6.2.0        # Font modern agar tidak kaku
  url_launcher: ^6.3.0        # Untuk membuka link pelacakan di Google Chrome
  image_picker: ^1.1.2        # Untuk seller mengambil foto resi fisik lewat kamera

  # INTI FIREBASE UNTUK DATA NYATA (SIAP RILIS INTERNET)
  firebase_core: ^3.0.0       # Pustaka utama Firebase
  firebase_auth: ^5.0.0       # Mengatur login akun nyata tanpa backend sendiri
  cloud_firestore: ^5.0.0     # Database cloud gratis untuk simpan chat, tiket, & logistik

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
