import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:url_launcher/url_launcher.dart';

const _blue=Color(0xFF126BFF);

class SuperAdminDashboard extends StatelessWidget{
 const SuperAdminDashboard({super.key});
 @override Widget build(BuildContext c)=>Scaffold(backgroundColor:const Color(0xFFF4F8FF),appBar:AppBar(backgroundColor:Colors.white,surfaceTintColor:Colors.white,title:Text('Nusopa Control Center',style:GoogleFonts.inter(fontWeight:FontWeight.w900,color:_blue)),actions:[IconButton(onPressed:()=>FirebaseAuth.instance.signOut(),icon:const Icon(Icons.logout))]),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('orders').snapshots(),builder:(c,o){final orders=o.data?.docs??[];final paid=orders.where((d)=>d.data()['status']=='MENUNGGU_VERIFIKASI').length;final dispute=orders.where((d)=>d.data()['status']=='DISPUTE').length;return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('withdrawals').snapshots(),builder:(c,w){final withdrawals=w.data?.docs.where((d)=>d.data()['status']=='MENUNGGU_ADMIN').length??0;return ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[_blue,Color(0xFF67C5FF)]),borderRadius:BorderRadius.circular(26)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Admin online',style:GoogleFonts.inter(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('Kendali transaksi, chat, pembayaran dan sengketa.',style:TextStyle(color:Colors.white70))])),const SizedBox(height:16),Row(children:[Expanded(child:_stat('Verifikasi',paid,Icons.receipt_long)),const SizedBox(width:10),Expanded(child:_stat('Dispute',dispute,Icons.gavel_outlined)),const SizedBox(width:10),Expanded(child:_stat('Withdraw',withdrawals,Icons.account_balance_wallet_outlined))]),const SizedBox(height:22),_menu(c,Icons.chat_rounded,'Inbox Chat','Balas chat pembeli dan penjual realtime',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const AdminInboxScreen()))),_menu(c,Icons.verified_rounded,'Verifikasi Pembayaran','Order menunggu verifikasi',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AdminOrdersScreen(filter:'MENUNGGU_VERIFIKASI')))),_menu(c,Icons.gavel_rounded,'Sengketa','Tangani DISPUTE',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AdminOrdersScreen(filter:'DISPUTE')))),_menu(c,Icons.account_balance_wallet_rounded,'Pencairan Seller','Review permintaan withdrawal',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const AdminWithdrawalsScreen()))) ]);});}));
 Widget _stat(String t,int v,IconData i)=>Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Column(children:[Icon(i,color:_blue),Text(v.toString(),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:20)),Text(t,style:const TextStyle(fontSize:10))]));
 Widget _menu(BuildContext c,IconData i,String t,String s,VoidCallback f)=>Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)),child:ListTile(onTap:f,leading:CircleAvatar(backgroundColor:_blue.withOpacity(.1),child:Icon(i,color:_blue)),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(s),trailing:const Icon(Icons.chevron_right)));
}

class AdminInboxScreen extends StatelessWidget{const AdminInboxScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Inbox Chat')),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('chats').orderBy('updatedAt',descending:true).snapshots(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());final docs=s.data?.docs??[];if(docs.isEmpty)return const Center(child:Text('Belum ada chat.'));return ListView.builder(itemCount:docs.length,itemBuilder:(_,i){final d=docs[i],x=d.data();return ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text((x['email']??d.id).toString()),subtitle:Text((x['lastMessage']??'').toString(),maxLines:1),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ChatRoomScreen(chatId:d.id,isAdmin:true))));});}));}

class ChatAdminScreen extends StatelessWidget{const ChatAdminScreen({super.key});Future<void> wa()async{final u=Uri.parse('https://wa.me/6285642131263?text=Halo%20Admin%20Nusopa.Mart%2C%20saya%20butuh%20bantuan.');await launchUrl(u,mode:LaunchMode.externalApplication);} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Bantuan Admin'),actions:[IconButton(icon:const Icon(Icons.headset_mic_rounded),onPressed:wa,tooltip:'WhatsApp Admin')]),body:Column(children:[Container(margin:const EdgeInsets.all(12),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFEAF3FF),borderRadius:BorderRadius.circular(16)),child:Row(children:[const Icon(Icons.headset_mic_rounded,color:_blue),const SizedBox(width:10),const Expanded(child:Text('Chat online dengan Admin Nusopa.Mart')),TextButton(onPressed:wa,child:const Text('WHATSAPP'))])),const Expanded(child:ChatRoomScreen(chatId:FirebaseAuth.instance.currentUser?.uid??'',isAdmin:false,embedded:true))]));}

class ChatRoomScreen extends StatefulWidget{final String chatId;final bool isAdmin,embedded;const ChatRoomScreen({super.key,required this.chatId,required this.isAdmin,this.embedded=false});@override State<ChatRoomScreen> createState()=>_ChatRoomScreenState();}
class _ChatRoomScreenState extends State<ChatRoomScreen>{final text=TextEditingController();XFile? image;bool sending=false;String get uid=>FirebaseAuth.instance.currentUser?.uid??'';
CollectionReference<Map<String,dynamic>> get msgs=>FirebaseFirestore.instance.collection('chats').doc(widget.chatId).collection('messages');
Future<void> pick()async{final f=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:75);if(f!=null)setState(()=>image=f);}
Future<void> send()async{if(text.text.trim().isEmpty&&image==null)return;setState(()=>sending=true);try{String imageUrl='';if(image!=null){final ref=FirebaseStorage.instance.ref('chat/'+uid+'/'+DateTime.now().millisecondsSinceEpoch.toString()+'.jpg');await ref.putFile(File(image!.path));imageUrl=await ref.getDownloadURL();}final body=text.text.trim();await FirebaseFirestore.instance.collection('chats').doc(widget.chatId).set({'ownerId':widget.isAdmin?widget.chatId:uid,'email':widget.isAdmin?'':FirebaseAuth.instance.currentUser?.email,'lastMessage':body.isEmpty?'📷 Foto':body,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));await msgs.add({'senderId':uid,'text':body,'imageUrl':imageUrl,'createdAt':FieldValue.serverTimestamp()});text.clear();setState(()=>image=null);}finally{if(mounted)setState(()=>sending=false);}}
@override Widget build(BuildContext c){final body=StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:msgs.orderBy('createdAt').snapshots(),builder:(c,s){final docs=s.data?.docs??[];return ListView.builder(padding:const EdgeInsets.all(12),itemCount:docs.length,itemBuilder:(_,i){final x=docs[i].data(),mine=x['senderId']==uid;return Align(alignment:mine?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.symmetric(vertical:4),padding:const EdgeInsets.all(10),constraints:BoxConstraints(maxWidth:MediaQuery.of(c).size.width*.76),decoration:BoxDecoration(color:mine?_blue:Colors.white,borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if((x['imageUrl']??'').toString().isNotEmpty)Image.network(x['imageUrl'],height:180,fit:BoxFit.cover),if((x['text']??'').toString().isNotEmpty)Text(x['text'],style:TextStyle(color:mine?Colors.white:Colors.black))])));});});final input=SafeArea(child:Padding(padding:const EdgeInsets.all(8),child:Row(children:[IconButton(onPressed:pick,icon:const Icon(Icons.photo_camera_outlined)),Expanded(child:TextField(controller:text,decoration:InputDecoration(hintText:'Tulis pesan...',border:OutlineInputBorder(borderRadius:BorderRadius.circular(22)))),),IconButton(onPressed:sending?null:send,icon:const Icon(Icons.send_rounded,color:_blue))])));return widget.embedded?Column(children:[Expanded(child:body),input]):Scaffold(appBar:AppBar(title:Text(widget.isAdmin?'Chat Pelanggan':'Chat Admin')),body:Column(children:[Expanded(child:body),input]));}
@override void dispose(){text.dispose();super.dispose();}
}

class AdminOrdersScreen extends StatelessWidget{final String filter;const AdminOrdersScreen({super.key,required this.filter});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(filter)),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('orders').where('status',isEqualTo:filter).snapshots(),builder:(c,s){final docs=s.data?.docs??[];return ListView.builder(itemCount:docs.length,itemBuilder:(_,i){final d=docs[i],x=d.data();return ListTile(title:Text((x['productName']??'Produk').toString()),subtitle:Text('Rp'+(x['total']??0).toString()),trailing:PopupMenuButton<String>(onSelected:(v)=>d.reference.update({'status':v,'updatedAt':FieldValue.serverTimestamp()}),itemBuilder:(_)=>const[PopupMenuItem(value:'DIBAYAR',child:Text('DIBAYAR')),PopupMenuItem(value:'DIBATALKAN',child:Text('DIBATALKAN')),PopupMenuItem(value:'SELESAI',child:Text('SELESAI'))]));});}));}}
class AdminWithdrawalsScreen extends StatelessWidget{const AdminWithdrawalsScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Withdrawal')),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('withdrawals').where('status',isEqualTo:'MENUNGGU_ADMIN').snapshots(),builder:(c,s){final docs=s.data?.docs??[];return ListView.builder(itemCount:docs.length,itemBuilder:(_,i){final d=docs[i],x=d.data();return ListTile(title:Text('Rp'+(x['amount']??0).toString()),subtitle:Text((x['bank']??'').toString()+' '+(x['accountNumber']??'').toString()),trailing:FilledButton(onPressed:()=>d.reference.update({'status':'DIPROSES','updatedAt':FieldValue.serverTimestamp()}),child:const Text('PROSES')));});}));}}