import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:google_fonts/google_fonts.dart';
class ChatScreen extends StatefulWidget{final String title;const ChatScreen({super.key,this.title='Chat Admin'});@override State<ChatScreen> createState()=>_ChatScreenState();}
class _ChatScreenState extends State<ChatScreen>{static const blue=Color(0xFF126BFF);final text=TextEditingController();XFile? image;bool sending=false;String get uid=>FirebaseAuth.instance.currentUser?.uid??'';CollectionReference<Map<String,dynamic>> get msgs=>FirebaseFirestore.instance.collection('chats').doc(uid).collection('messages');
Future<void> pick()async{try{final f=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:82,maxWidth:1600);if(f!=null&&mounted)setState(()=>image=f);}catch(e){_err('Gagal memilih gambar: $e');}}
Future<void> send()async{final body=text.text.trim();if(uid.isEmpty||sending||(body.isEmpty&&image==null))return;setState(()=>sending=true);try{var url='';final f=image;if(f!=null){final r=FirebaseStorage.instance.ref('chat/$uid/${DateTime.now().millisecondsSinceEpoch}.jpg');await r.putFile(File(f.path),SettableMetadata(contentType:'image/jpeg'));url=await r.getDownloadURL();}await FirebaseFirestore.instance.collection('chats').doc(uid).set({'ownerId':uid,'email':FirebaseAuth.instance.currentUser?.email??'','lastMessage':body.isEmpty?'📷 Foto':body,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));await msgs.add({'senderId':uid,'text':body,'imageUrl':url,'createdAt':FieldValue.serverTimestamp()});text.clear();if(mounted)setState(()=>image=null);}catch(e){_err('Pesan gagal dikirim. Periksa koneksi/izin Firebase.\n$e');}finally{if(mounted)setState(()=>sending=false);}}
void _err(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s),behavior:SnackBarBehavior.floating));
@override Widget build(BuildContext c)=>Scaffold(backgroundColor:const Color(0xFFF7FAFF),appBar:AppBar(backgroundColor:Colors.white,surfaceTintColor:Colors.white,title:Text(widget.title,style:GoogleFonts.inter(fontWeight:FontWeight.w800))),body:Column(children:[Expanded(child:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:msgs.orderBy('createdAt').snapshots(),builder:(c,s){if(s.hasError)return Center(child:Text('Chat belum dapat dimuat: ${s.error}'));final ds=s.data?.docs??const[];if(ds.isEmpty)return const Center(child:Text('Belum ada pesan.\nKirim pesan atau foto untuk menghubungi Admin.',textAlign:TextAlign.center));return ListView.builder(padding:const EdgeInsets.all(12),itemCount:ds.length,itemBuilder:(_,i){final d=ds[i].data(),mine=d['senderId']==uid,url=(d['imageUrl']??'').toString(),body=(d['text']??'').toString();return Align(alignment:mine?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(10),constraints:BoxConstraints(maxWidth:MediaQuery.of(c).size.width*.78),decoration:BoxDecoration(color:mine?blue:Colors.white,borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(url.isNotEmpty)ClipRRect(borderRadius:BorderRadius.circular(10),child:Image.network(url,height:190,width:240,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const SizedBox(height:70,child:Center(child:Icon(Icons.broken_image_outlined)))),if(body.isNotEmpty)Padding(padding:EdgeInsets.only(top:url.isNotEmpty?8:0),child:Text(body,style:TextStyle(color:mine?Colors.white:Colors.black87))) ])));});})),if(image!=null)Container(color:Colors.white,padding:const EdgeInsets.all(8),child:Row(children:[Image.file(File(image!.path),width:55,height:55,fit:BoxFit.cover),const SizedBox(width:8),const Expanded(child:Text('Foto siap dikirim')),IconButton(onPressed:()=>setState(()=>image=null),icon:const Icon(Icons.close))])),SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,8),child:Row(children:[IconButton(onPressed:sending?null:pick,icon:const Icon(Icons.photo_outlined,color:blue)),Expanded(child:TextField(controller:text,maxLines:4,minLines:1,decoration:InputDecoration(hintText:'Tulis pesan...',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(22),borderSide:BorderSide.none)))),IconButton(onPressed:sending?null:send,icon:const Icon(Icons.send_rounded,color:blue))]))) ]));
@override void dispose(){text.dispose();super.dispose();}}
