import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../services/cart_service.dart';
import '../services/rekber_service.dart';

class CheckoutScreen extends StatefulWidget {
 final String? sellerId,productId,productName; final int? price; final List<Map<String,dynamic>>? items;
 const CheckoutScreen({super.key,this.sellerId,this.productId,this.productName,this.price,this.items});
 const CheckoutScreen.cart({super.key,required this.items}):sellerId=null,productId=null,productName=null,price=null;
 @override State<CheckoutScreen> createState()=>_CheckoutScreenState();
}
class _CheckoutScreenState extends State<CheckoutScreen>{
 static const blue=Color(0xFF126BFF); int qty=1; final shipping=TextEditingController(text:'0'); bool loading=false;
 int val(dynamic v)=>v is num?v.toInt():int.tryParse(v.toString())??0;
 String money(int n)=>'Rp${n.toString().replaceAllMapped(RegExp(r'(?=(\d{3})+(?!\d))'),(_)=>'.')}';
 Future<List<Map<String,dynamic>>> resolve()async{if(widget.items!=null){final out=<Map<String,dynamic>>[];for(final raw in widget.items!){final id=(raw['productId']??raw['cartId']??'').toString();final s=await FirebaseFirestore.instance.collection('products').doc(id).get();final p=s.data();if(p==null||!s.exists)throw Exception('Produk tidak tersedia');final price=val(p['price']??p['productPrice']),stock=val(p['stock']),q=val(raw['qty']);if(price<=0||q<=0||stock<q)throw Exception('Stok tidak mencukupi untuk ${p['name']??'produk'}');out.add({'productId':id,'sellerId':(p['sellerId']??'').toString(),'productName':(p['name']??p['productName']??'Produk').toString(),'price':price,'qty':q});}return out;}if(widget.sellerId==null||widget.productId==null||widget.productName==null||widget.price==null)throw Exception('Data checkout tidak lengkap');return [{'sellerId':widget.sellerId!,'productId':widget.productId!,'productName':widget.productName!,'price':widget.price!,'qty':qty}];}
 Future<void> submit()async{final ship=val(shipping.text);if(ship<0)return;setState(()=>loading=true);try{final items=await resolve();final ids=<String>[];for(final i in items){ids.add(await RekberService.instance.createOrder(sellerId:i['sellerId'],productId:i['productId'],productName:i['productName'],price:i['price'],qty:i['qty'],shippingCost:ship));}if(widget.items!=null)await CartService.instance.clear();if(!mounted)return;await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Order berhasil dibuat'),content:Text('ID Order: ${ids.join(', ')}\nTotal sudah termasuk biaya Rekber Rp3.000 per order. Ikuti instruksi pembayaran resmi Admin.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('OK'))]));if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Checkout gagal: $e'),behavior:SnackBarBehavior.floating));}finally{if(mounted)setState(()=>loading=false);}}
 @override Widget build(BuildContext c){final cart=widget.items!=null;return Scaffold(backgroundColor:const Color(0xFFF5F8FF),appBar:AppBar(backgroundColor:Colors.white,surfaceTintColor:Colors.white,title:const Text('Checkout')),body:ListView(padding:const EdgeInsets.all(16),children:[if(cart)...widget.items!.map((i)=>Card(elevation:0,child:ListTile(title:Text('${i['productName']??'Produk'}'),subtitle:Text('Jumlah ${val(i['qty'])}'),trailing:Text(money(val(i['price'])*val(i['qty'])),style:const TextStyle(fontWeight:FontWeight.w800,color:blue)))) else Card(elevation:0,child:ListTile(title:Text(widget.productName??'Produk'),subtitle:Text(money((widget.price??0)*qty)),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:qty>1?()=>setState(()=>qty--):null,icon:const Icon(Icons.remove_circle_outline)),Text('$qty'),IconButton(onPressed:()=>setState(()=>qty++),icon:const Icon(Icons.add_circle_outline))]))),const SizedBox(height:10),_summary(),const SizedBox(height:12),TextField(controller:shipping,onChanged:(_)=>setState((){}),keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Biaya ekspedisi',prefixText:'Rp ',filled:true,fillColor:Colors.white,border:OutlineInputBorder())),const SizedBox(height:12),const Card(elevation:0,child:Padding(padding:EdgeInsets.all(16),child:Text('Biaya Rekber: Rp3.000 per order. Pembayaran hanya melalui instruksi resmi Admin. Jangan kirim OTP, PIN, atau dana kepada pihak lain.'))),const SizedBox(height:20),FilledButton.icon(onPressed:loading?null:submit,style:FilledButton.styleFrom(backgroundColor:blue,padding:const EdgeInsets.symmetric(vertical:15)),icon:loading?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.lock_outline),label:Text(loading?'MEMPROSES...':'BUAT ORDER DENGAN REKBER'))]));}
 Widget _summary(){var subtotal=0,fee=3000;if(widget.items!=null){subtotal=widget.items!.fold(0,(s,i)=>s+val(i['price'])*val(i['qty']));fee=widget.items!.length*3000;}else subtotal=(widget.price??0)*qty;final ship=val(shipping.text);return Card(elevation:0,child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[_row('Subtotal produk',money(subtotal)),_row('Biaya Rekber',money(fee)),_row('Ekspedisi',money(ship)),const Divider(),_row('Total pembayaran',money(subtotal+fee+ship))])));}
 Widget _row(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(children:[Expanded(child:Text(a,style:GoogleFonts.inter(fontSize:13))),Text(b,style:GoogleFonts.inter(fontWeight:FontWeight.w800))]));
 @override void dispose(){shipping.dispose();super.dispose();}
}
