import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'account_screen.dart';
import 'cart_screen.dart';
import 'chat_screen.dart';
import 'orders_screen.dart';
import 'product_detail_screen.dart';
import 'seller_dashboard.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  static const blue=Color(0xFF126BFF), bg=Color(0xFFF4F8FF);
  int tab=0; final search=TextEditingController(); String query='';
  @override void dispose(){search.dispose();super.dispose();}
  @override Widget build(BuildContext c)=>Scaffold(backgroundColor:bg,appBar:AppBar(backgroundColor:Colors.white,surfaceTintColor:Colors.white,title:Container(height:40,decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(9)),child:TextField(controller:search,onChanged:(v)=>setState(()=>query=v.toLowerCase().trim()),decoration:InputDecoration(border:InputBorder.none,prefixIcon:const Icon(Icons.search,color:blue),hintText:'Cari produk, toko, atau kategori...',hintStyle:GoogleFonts.inter(fontSize:13),suffixIcon:query.isEmpty?null:IconButton(onPressed:(){search.clear();setState(()=>query='');},icon:const Icon(Icons.close))))),actions:[IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const CartScreen())),icon:const Icon(Icons.shopping_bag_outlined,color:blue),tooltip:'Keranjang'),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ChatScreen())),icon:const Icon(Icons.headset_mic_rounded,color:blue)),const SizedBox(width:5)]),body:[_HomeContent(query:query),const OrdersScreen(),const ChatScreen(),const AccountScreen()][tab],bottomNavigationBar:BottomNavigationBar(currentIndex:tab,onTap:(v)=>setState(()=>tab=v),type:BottomNavigationBarType.fixed,backgroundColor:Colors.white,elevation:0,selectedItemColor:blue,unselectedItemColor:Colors.grey.shade400,items:const[BottomNavigationBarItem(icon:Icon(Icons.home_outlined),activeIcon:Icon(Icons.home),label:'Home'),BottomNavigationBarItem(icon:Icon(Icons.inventory_2_outlined),activeIcon:Icon(Icons.inventory_2),label:'Pesanan'),BottomNavigationBarItem(icon:Icon(Icons.headset_mic_outlined),activeIcon:Icon(Icons.headset_mic),label:'Bantuan'),BottomNavigationBarItem(icon:Icon(Icons.person_outline),activeIcon:Icon(Icons.person),label:'Saya')]));
}
class _HomeContent extends StatefulWidget { final String query; const _HomeContent({required this.query}); @override State<_HomeContent> createState()=>_HomeContentState(); }
class _HomeContentState extends State<_HomeContent>{
 static const blue=Color(0xFF126BFF); final page=PageController(viewportFraction:.92); Timer? timer; int seconds=5124;
 @override void initState(){super.initState();timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted&&seconds>0)setState(()=>seconds--);});}
 @override void dispose(){timer?.cancel();page.dispose();super.dispose();}
 int val(dynamic v)=>v is num?v.toInt():int.tryParse(v.toString())??0;
 String money(dynamic v){final n=val(v);return 'Rp${n.toString().replaceAllMapped(RegExp(r'(?=(\d{3})+(?!\d))'),(_)=>'.')}';}
 @override Widget build(BuildContext c)=>RefreshIndicator(onRefresh:()async=>setState((){}),child:CustomScrollView(slivers:[
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,16,16,8),child:SizedBox(height:165,child:PageView(controller:page,children:[_banner('BELANJA AMAN DENGAN REKBER','Dana mengikuti alur transaksi Nusopa.Mart',Icons.shield_outlined),_banner('JUAL BARANGMU','Upload foto, atur stok dan terima pesanan',Icons.storefront_outlined),_banner('TRANSAKSI LEBIH TENANG','Gunakan bantuan Admin saat ada masalah',Icons.verified_user_outlined)])))),
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.symmetric(vertical:15,horizontal:16),child:Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[_cat(Icons.shield_outlined,'Rekber',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ChatScreen()))),_cat(Icons.local_fire_department_outlined,'Promo',()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Promo resmi akan tampil saat tersedia.')))),_cat(Icons.inventory_2_outlined,'Pesanan',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const OrdersScreen()))),_cat(Icons.add_business_outlined,'Jual',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SellerDashboard())))]))),
  SliverToBoxAdapter(child:Container(margin:const EdgeInsets.fromLTRB(16,0,16,4),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:blue,borderRadius:BorderRadius.circular(18)),child:Row(children:[const Icon(Icons.bolt,color:Color(0xFFFFC107),size:30),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('FLASH PROMO',style:GoogleFonts.inter(color:Colors.white,fontWeight:FontWeight.w800)),Text('Promo dan voucher resmi dari Admin',style:GoogleFonts.inter(color:Colors.white70,fontSize:10))])),Text(_timer(),style:GoogleFonts.inter(color:Colors.white,fontWeight:FontWeight.w800))]))),
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,12,16,0),child:Row(children:[_voucher('🎁 VOUCHER','Promo pengguna baru'),const SizedBox(width:10),_voucher('🛡️ REKBER','Perlindungan transaksi')]))),
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.all(16),child:Text('REKOMENDASI UNTUK KAMU',style:GoogleFonts.inter(fontSize:13,fontWeight:FontWeight.w800,letterSpacing:1.1,color:blue)))),
  StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('products').snapshots(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return SliverPadding(padding:const EdgeInsets.symmetric(horizontal:16),sliver:SliverGrid(gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,childAspectRatio:.64,crossAxisSpacing:12,mainAxisSpacing:12),delegate:SliverChildBuilderDelegate((_,__)=>_skeleton(),childCount:6)));if(s.hasError)return SliverToBoxAdapter(child:_empty('Produk belum dapat dimuat',Icons.cloud_off_outlined));var docs=s.data?.docs??const[];docs=docs.where((d){final x=d.data(),name=(x['name']??x['productName']??'').toString(),image=(x['imageUrl']??x['image']??'').toString(),seller=(x['sellerId']??'').toString();final p=val(x['price']??x['productPrice']);return name.trim().isNotEmpty&&image.trim().isNotEmpty&&seller.isNotEmpty&&p>0&&x['active']!=false&&(widget.query.isEmpty||('$name ${x['category']??''} ${x['storeName']??''}').toLowerCase().contains(widget.query));}).toList();if(docs.isEmpty)return SliverToBoxAdapter(child:_empty(widget.query.isEmpty?'Belum ada produk aktif':'Produk tidak ditemukan',Icons.inventory_2_outlined));return SliverPadding(padding:const EdgeInsets.symmetric(horizontal:16),sliver:SliverGrid(gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,childAspectRatio:.61,crossAxisSpacing:12,mainAxisSpacing:12),delegate:SliverChildBuilderDelegate((c,i)=>_product(c,docs[i]),childCount:docs.length)));}),const SliverToBoxAdapter(child:SizedBox(height:45))]));
 Widget _product(BuildContext c,QueryDocumentSnapshot<Map<String,dynamic>> d){final x=d.data(),name=(x['name']??x['productName']??'Produk').toString(),image=(x['imageUrl']??x['image']??'').toString();return InkWell(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ProductDetailScreen(productId:d.id,product:x))),child:Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:ClipRRect(borderRadius:const BorderRadius.vertical(top:Radius.circular(15)),child:Image.network(image,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:Colors.grey.shade100,child:const Icon(Icons.broken_image_outlined))))),Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,maxLines:2,overflow:TextOverflow.ellipsis,style:GoogleFonts.inter(fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:5),Text(money(x['price']??x['productPrice']),style:GoogleFonts.inter(color:blue,fontWeight:FontWeight.w900,fontSize:14)),const SizedBox(height:5),Text('⭐ ${(x['rating']??5.0)}  •  Terjual ${(x['sold']??0)}',style:GoogleFonts.inter(fontSize:9,color:Colors.grey)),const SizedBox(height:6),const Text('🛡 Rekber Aman',style:TextStyle(fontSize:9,color:Color(0xFF16803A),fontWeight:FontWeight.w700))]))])));}
 Widget _banner(String a,String b,IconData i)=>Container(margin:const EdgeInsets.only(right:10),padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[blue,Color(0xFF62B6FF)]),borderRadius:BorderRadius.circular(14)),child:Row(children:[Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:GoogleFonts.inter(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text(b,style:GoogleFonts.inter(color:Colors.white70,fontSize:11))])),Icon(i,color:Colors.white,size:42)]));
 Widget _cat(IconData i,String t,VoidCallback f)=>InkWell(onTap:f,child:Column(children:[Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12)),child:Icon(i,color:blue,size:24)),const SizedBox(height:7),Text(t,style:GoogleFonts.inter(fontSize:11,fontWeight:FontWeight.w600))]));
 Widget _voucher(String a,String b)=>Expanded(child:Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14),border:Border.all(color:blue.withValues(alpha:.1))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:GoogleFonts.inter(color:blue,fontWeight:FontWeight.w800,fontSize:10)),const SizedBox(height:4),Text(b,style:GoogleFonts.inter(color:Colors.grey,fontSize:9))])));
 Widget _skeleton()=>Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15)),padding:const EdgeInsets.all(10),child:Column(children:[Expanded(child:Container(color:Colors.grey.shade200)),const SizedBox(height:8),Container(height:10,color:Colors.grey.shade200),const SizedBox(height:6),Container(height:10,width:80,color:Colors.grey.shade200)]));
 Widget _empty(String t,IconData i)=>Padding(padding:const EdgeInsets.all(34),child:Column(children:[Icon(i,size:46,color:Colors.grey.shade400),const SizedBox(height:10),Text(t,style:GoogleFonts.inter(fontWeight:FontWeight.w700)),const SizedBox(height:5),const Text('Produk seller yang aktif akan tampil di sini.') ]));
 String _timer(){final h=(seconds~/3600).toString().padLeft(2,'0'),m=((seconds%3600)~/60).toString().padLeft(2,'0'),s=(seconds%60).toString().padLeft(2,'0');return '$h:$m:$s';}
}
