import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class SellerProductsScreen extends StatelessWidget {
  const SellerProductsScreen({super.key});
  @override Widget build(BuildContext context){
    final uid=FirebaseAuth.instance.currentUser!.uid;
    return Scaffold(appBar:AppBar(title:const Text('Produk Saya')),floatingActionButton:FloatingActionButton.extended(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ProductEditorScreen())),icon:const Icon(Icons.add),label:const Text('Produk')),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('products').where('sellerId',isEqualTo:uid).snapshots(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());final docs=s.data?.docs??[];if(docs.isEmpty)return const Center(child:Text('Belum ada produk.'));return ListView.builder(itemCount:docs.length,itemBuilder:(_,i){final d=docs[i],x=d.data(),url=(x['imageUrl']??'').toString();return ListTile(leading:url.isEmpty?const Icon(Icons.image):Image.network(url,width:50,height:50,fit:BoxFit.cover),title:Text((x['name']??'Produk').toString()),subtitle:Text('Rp'+(x['price']??0).toString()+' • Stok '+(x['stock']??0).toString()),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>d.reference.delete()),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ProductEditorScreen(id:d.id,data:x))));});}));
  }
}
class ProductEditorScreen extends StatefulWidget { final String? id; final Map<String,dynamic>? data; const ProductEditorScreen({super.key,this.id,this.data}); @override State<ProductEditorScreen> createState()=>_ProductEditorScreenState(); }
class _ProductEditorScreenState extends State<ProductEditorScreen>{
  late final TextEditingController name,price,stock,desc; XFile? image; bool saving=false;
  @override void initState(){super.initState();final x=widget.data??{};name=TextEditingController(text:(x['name']??'').toString());price=TextEditingController(text:(x['price']??'').toString());stock=TextEditingController(text:(x['stock']??'').toString());desc=TextEditingController(text:(x['description']??'').toString());}
  Future<void> pick()async{final f=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:80);if(f!=null)setState(()=>image=f);}
  Future<void> save()async{if(name.text.trim().isEmpty)return;setState(()=>saving=true);try{final uid=FirebaseAuth.instance.currentUser!.uid;String url=(widget.data?['imageUrl']??'').toString();if(image!=null){final ref=FirebaseStorage.instance.ref('products/'+uid+'/'+DateTime.now().millisecondsSinceEpoch.toString()+'.jpg');await ref.putFile(File(image!.path));url=await ref.getDownloadURL();}final data=<String,dynamic>{'sellerId':uid,'name':name.text.trim(),'price':int.tryParse(price.text)??0,'stock':int.tryParse(stock.text)??0,'description':desc.text.trim(),'imageUrl':url,'updatedAt':FieldValue.serverTimestamp()};if(widget.id==null){data['createdAt']=FieldValue.serverTimestamp();await FirebaseFirestore.instance.collection('products').add(data);}else{await FirebaseFirestore.instance.collection('products').doc(widget.id).update(data);}if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>saving=false);}}
  @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.id==null?'Tambah Produk':'Edit Produk')),body:ListView(padding:const EdgeInsets.all(16),children:[GestureDetector(onTap:pick,child:Container(height:180,color:Colors.blue.shade50,child:image!=null?Image.file(File(image!.path),fit:BoxFit.cover):(widget.data?['imageUrl']??'').toString().isNotEmpty?Image.network(widget.data!['imageUrl'],fit:BoxFit.cover):const Center(child:Icon(Icons.add_photo_alternate_outlined,size:48)))),const SizedBox(height:12),TextField(controller:name,decoration:const InputDecoration(labelText:'Nama produk')),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Harga')),TextField(controller:stock,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Stok')),TextField(controller:desc,maxLines:4,decoration:const InputDecoration(labelText:'Deskripsi')),const SizedBox(height:20),FilledButton(onPressed:saving?null:save,child:Text(saving?'Menyimpan...':'SIMPAN'))]));}
