import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../services/social_service.dart';
import '../widgets/social_widgets.dart';
import 'chat_screen.dart';
import 'direct_chat_screen.dart';
import 'edit_profile_screen.dart';
import 'home_screen.dart';
import 'orders_screen.dart';
import 'rekber_info_screen.dart';
import 'seller_dashboard.dart';

class SocialProfileScreen extends StatefulWidget {
  final String? userId; final String? userName;
  const SocialProfileScreen({super.key, this.userId, this.userName});
  @override State<SocialProfileScreen> createState() => _SocialProfileScreenState();
}
class _SocialProfileScreenState extends State<SocialProfileScreen> {
  int tab = 0; bool? following;
  String get uid => FirebaseAuth.instance.currentUser?.uid ?? '';
  String get profileUid => widget.userId ?? uid;
  bool get own => profileUid == uid;
  @override void initState() { super.initState(); _refreshFollow(); }
  Future<void> _refreshFollow() async { if (own || profileUid.isEmpty) return; final v = await SocialService.instance.isFollowing(profileUid); if (mounted) setState(() => following = v); }

  @override Widget build(BuildContext context) => Scaffold(backgroundColor: SocialTheme.background, appBar: AppBar(backgroundColor: Colors.white, surfaceTintColor: Colors.white, title: StreamBuilder<DocumentSnapshot<Map<String,dynamic>>>(stream: FirebaseFirestore.instance.collection('social_profiles').doc(profileUid).snapshots(), builder: (_,s) => Text((s.data?.data()?['displayName'] ?? widget.userName ?? 'Profil').toString(), style: GoogleFonts.inter(fontWeight: FontWeight.w800))), actions: [IconButton(onPressed: () => _menu(context), icon: const Icon(Icons.more_horiz))]), body: StreamBuilder<DocumentSnapshot<Map<String,dynamic>>>(stream: FirebaseFirestore.instance.collection('social_profiles').doc(profileUid).snapshots(), builder: (context,s) { final p=s.data?.data() ?? {}; final name=(p['displayName'] ?? widget.userName ?? 'Pengguna').toString(); return CustomScrollView(slivers: [SliverToBoxAdapter(child: _header(p,name)), SliverToBoxAdapter(child: Container(color: Colors.white, child: Row(children: [SocialTab(label:'Postingan Sosial', selected:tab==0, onTap:()=>setState(()=>tab=0)), SocialTab(label:'Produk Jualan', selected:tab==1, onTap:()=>setState(()=>tab=1))]))), if(tab==0) _posts() else _products()]); });

  Widget _header(Map<String,dynamic> p,String name) { final cover=(p['coverPhotoUrl']??'').toString(); final photo=(p['photoUrl']??'').toString(); final bio=(p['bio']??'').toString(); final rating=(p['rekberRating'] as num?)?.toDouble() ?? 0; return Container(color:Colors.white,child:Column(children:[Stack(clipBehavior:Clip.none,children:[SizedBox(height:190,width:double.infinity,child:cover.isEmpty?Container(color:const Color(0xFFE7EEF9)):Image.network(cover,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:const Color(0xFFE7EEF9)))),Positioned(left:18,bottom:-48,child:Container(padding:const EdgeInsets.all(3),decoration:const BoxDecoration(color:Colors.white,shape:BoxShape.circle),child:SocialAvatar(imageUrl:photo,radius:48)))]),Padding(padding:const EdgeInsets.fromLTRB(18,58,18,14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:GoogleFonts.inter(fontSize:21,fontWeight:FontWeight.w900)),if(bio.isNotEmpty)...[const SizedBox(height:5),Text(bio,style:GoogleFonts.inter(fontSize:11,color:SocialTheme.muted,height:1.4))],const SizedBox(height:14),Row(children:[_count('followers','Pengikut'),_count('following','Mengikuti'),Expanded(child:Column(children:[Text(rating>0?rating.toStringAsFixed(1):'—',style:GoogleFonts.inter(fontSize:15,fontWeight:FontWeight.w900)),Text('Rating Rekber',style:GoogleFonts.inter(fontSize:9,color:SocialTheme.muted))]))]),const SizedBox(height:12),_actions(name)]))])); }
  Widget _actions(String name) => own ? Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const EditProfileScreen())),icon:const Icon(Icons.edit_outlined),label:const Text('Edit Profil'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:()=>_menu(context),icon:const Icon(Icons.shield_outlined),label:const Text('Rekber')))]) : Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()async{await SocialService.instance.toggleFollow(profileUid);await _refreshFollow();},icon:Icon(following==true?Icons.check:Icons.person_add_alt_1),label:Text(following==true?'Mengikuti':'Ikuti'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DirectChatScreen(otherUid:profileUid,title:name))),icon:const Icon(Icons.chat_bubble_outline),label:const Text('Kirim Pesan')))]);
  Widget _count(String c,String label)=>Expanded(child:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('social_profiles').doc(profileUid).collection(c).snapshots(),builder:(_,s)=>Column(children:[Text('${s.data?.docs.length??0}',style:GoogleFonts.inter(fontSize:15,fontWeight:FontWeight.w900)),Text(label,style:GoogleFonts.inter(fontSize:9,color:SocialTheme.muted))])));

  Widget _posts()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('posts').where('authorId',isEqualTo:profileUid).snapshots(),builder:(_,s){final docs=[...(s.data?.docs??<QueryDocumentSnapshot<Map<String,dynamic>>>[])];docs.sort((a,b)=>((b.data()['createdAt'] as Timestamp?)?.millisecondsSinceEpoch??0).compareTo((a.data()['createdAt'] as Timestamp?)?.millisecondsSinceEpoch??0));if(docs.isEmpty)return _empty('Belum ada postingan.');return SliverList(delegate:SliverChildBuilderDelegate((_,i)=>Padding(padding:const EdgeInsets.fromLTRB(12,10,12,0),child:_post(docs[i])),childCount:docs.length));});
  Widget _post(QueryDocumentSnapshot<Map<String,dynamic>> doc){final d=doc.data();final imgs=(d['imageUrls'] as List?)?.map((e)=>e.toString()).where((e)=>e.isNotEmpty).toList()??<String>[];return SocialCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[SocialPostHeader(avatar:(d['authorPhotoUrl']??'').toString(),name:(d['authorName']??'Pengguna').toString(),time:'',onMore:()=>_postMenu(doc.id,(d['authorId']??'').toString())),if((d['text']??'').toString().trim().isNotEmpty)...[const SizedBox(height:5),Text(d['text'].toString(),style:GoogleFonts.inter(fontSize:13,height:1.45))],if(imgs.isNotEmpty)...[const SizedBox(height:10),SocialImageGrid(images:imgs)],SocialInteractionBar(likes:(d['likeCount'] as num?)?.toInt()??0,comments:(d['commentCount'] as num?)?.toInt()??0,onLike:()=>SocialService.instance.toggleLike(doc.id,authorId:(d['authorId']??'').toString()),onComment:()=>{},onShare:()=>SocialService.instance.sharePost(doc.id,authorId:(d['authorId']??'').toString()))]));}
  Widget _products()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('products').where('sellerId',isEqualTo:profileUid).snapshots(),builder:(_,s){final docs=s.data?.docs??<QueryDocumentSnapshot<Map<String,dynamic>>>[];if(docs.isEmpty)return _empty('Belum ada produk jualan aktif.');return SliverPadding(padding:const EdgeInsets.all(12),sliver:SliverGrid(delegate:SliverChildBuilderDelegate((context,i){final d=docs[i].data();final url=(d['imageUrl']??'').toString();return SocialCard(padding:EdgeInsets.zero,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:url.isEmpty?const Center(child:Icon(Icons.image_outlined,size:42)):Image.network(url,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Center(child:Icon(Icons.broken_image_outlined)))),Padding(padding:const EdgeInsets.all(9),child:Text((d['name']??'Produk').toString(),maxLines:2,overflow:TextOverflow.ellipsis,style:GoogleFonts.inter(fontWeight:FontWeight.w800,fontSize:12))) ]));},childCount:docs.length),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:.75)));});
  Widget _empty(String text)=>SliverToBoxAdapter(child:SocialCard(child:Padding(padding:const EdgeInsets.all(20),child:Center(child:Text(text,textAlign:TextAlign.center,style:GoogleFonts.inter(color:SocialTheme.muted))))));
  void _postMenu(String id,String authorId){showModalBottomSheet(context:context,builder:(_)=>SafeArea(child:ListTile(leading:Icon(authorId==uid?Icons.delete_outline:Icons.flag_outlined),title:Text(authorId==uid?'Hapus postingan':'Laporkan postingan'),onTap:()async{Navigator.pop(context);if(authorId==uid)await FirebaseFirestore.instance.collection('posts').doc(id).delete();})));}
  void _menu(BuildContext context){final items=own?<Widget>[
    ListTile(leading:const Icon(Icons.edit_outlined),title:const Text('Edit Profil'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const EditProfileScreen()))),
    ListTile(leading:const Icon(Icons.storefront_outlined),title:const Text('Belanja & Marketplace'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const HomeScreen()))),
    ListTile(leading:const Icon(Icons.receipt_long_outlined),title:const Text('Pesanan Saya'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OrdersScreen()))),
    ListTile(leading:const Icon(Icons.store_outlined),title:const Text('Kelola Produk & Toko'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SellerDashboard()))),
    ListTile(leading:const Icon(Icons.shield_outlined),title:const Text('Rekber & Perlindungan Transaksi'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const RekberInfoScreen()))),
    ListTile(leading:const Icon(Icons.headset_mic_outlined),title:const Text('Chat Admin'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ChatScreen()))),
  ]:<Widget>[ListTile(leading:const Icon(Icons.flag_outlined),title:const Text('Laporkan profil'),onTap:()=>Navigator.pop(context)),ListTile(leading:const Icon(Icons.block_outlined),title:const Text('Blokir pengguna'),onTap:()=>Navigator.pop(context))];showModalBottomSheet(context:context,builder:(_)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:items)));}
}
