name: Flutter Build APK Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Membuat folder android standar bawaan Flutter terbaru secara aman
    - name: Auto Generate Android and Fix Sample Main Dart
      run: |
        flutter create . --platforms=android
        
        # Sembuhin baris sample main.dart bawaan Flutter CLI yang rusak titik eksperimental
        sed -i 's/colorScheme: .fromSeed/colorScheme: ColorScheme.fromSeed/g' lib/main.dart
        sed -i 's/mainAxisAlignment: .center/mainAxisAlignment: MainAxisAlignment.center/g' lib/main.dart

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK Release
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
