name: Rakit Otomatis APK Nusopa Mart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil seluruh kode dari repositori GitHub Anda
      - name: Ambil Kode Repositori
        uses: actions/checkout@v4

      # 2. Memasang bahasa pemrograman Java
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Memasang Mesin Flutter ke server cloud GitHub
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0'

      # 4. Membuat kerangka folder Android asli bawaan pabrik Flutter
      - name: Buat Paksa Kerangka Folder Android Native
        run: flutter create . --platforms=android --project-name=nusopa_mart

      # 5. AMANKAN SUARA: Membuat folder assets/suara & file mp3 kosong otomatis agar pubspec tidak eror
      - name: Amankan Aset Folder Suara
        run: |
          mkdir -p assets/suara
          touch assets/suara/nusopa_sound.mp3

      # 6. SUNTIK SDK 34 AMAN: Menyesuaikan build.gradle aplikasi agar terkunci di SDK 34 yang stabil
      - name: Suntik Paksa Versi SDK Android Stable
        run: |
          sed -i 's/compileSdkVersion .*/compileSdkVersion 34/g' android/app/build.gradle || true
          sed -i 's/minSdkVersion .*/minSdkVersion 23/g' android/app/build.gradle || true
          sed -i 's/targetSdkVersion .*/targetSdkVersion 34/g' android/app/build.gradle || true

      # 7. Mengunduh semua pustaka yang tertulis di pubspec.yaml Anda
      - name: Install Pustaka (Dependencies)
        run: flutter pub get

      # 8. Memicu robot pembangun untuk memotong logo.png menjadi ikon aplikasi Android resmi
      - name: Cetak Logo Ikon Aplikasi Otomatis
        run: flutter pub run flutter_launcher_icons

      # 9. PROSES UTAMA (TRIK JEBOL KOTLIN): Merakit APK sambil menyuntikkan paksa versi Kotlin 1.9.0 lewat argumen build
      - name: Proses Perakitan APK (Build Release)
        run: flutter build apk --release --no-tree-shake-icons --PkotlinVersion=1.9.0

      # 10. Memanen hasil rakitan dan memajangnya di halaman GitHub agar bisa Anda unduh
      - name: Upload File APK Siap Pakai
        uses: actions/upload-artifact@v4
        with:
          name: Nusopa-Mart-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
